# Generated by Django 5.0.6 on 2024-06-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_uuid', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
    ]
